import { Currency } from "./types/TCreateProject";

export const CURRENCY_OPTIONS: Currency[] = [
  { name: "Australian Dollar", code: "AUD", symbol: "$" },
  { name: "Brazilian Real", code: "BRL", symbol: "R$" },
  { name: "British Pound", code: "GBP", symbol: "£" },
  { name: "Canadian Dollar", code: "CAD", symbol: "CA$" },
  { name: "Chinese Yuan", code: "CNY", symbol: "¥" },
  { name: "Czech Koruna", code: "CZK", symbol: "Kč" },
  { name: "Danish Krone", code: "DKK", symbol: "kr" },
  { name: "Euro", code: "EUR", symbol: "€" },
  { name: "Hong Kong Dollar", code: "HKD", symbol: "HK$" },
  { name: "Hungarian Forint", code: "HUF", symbol: "Ft" },
  { name: "Indian Rupee", code: "INR", symbol: "₹" },
  { name: "Indonesian Rupiah", code: "IDR", symbol: "Rp" },
  { name: "Israeli New Shekel", code: "ILS", symbol: "₪" },
  { name: "Japanese Yen", code: "JPY", symbol: "¥" },
  { name: "Malaysian Ringgit", code: "MYR", symbol: "RM" },
  { name: "Mexican Peso", code: "MXN", symbol: "MX$" },
  { name: "New Zealand Dollar", code: "NZD", symbol: "NZ$" },
  { name: "Norwegian Krone", code: "NOK", symbol: "kr" },
  { name: "Philippine Peso", code: "PHP", symbol: "₱" },
  { name: "Polish Złoty", code: "PLN", symbol: "zł" },
  { name: "Russian Ruble", code: "RUB", symbol: "₽" },
  { name: "Saudi Riyal", code: "SAR", symbol: "﷼" },
  { name: "Singapore Dollar", code: "SGD", symbol: "S$" },
  { name: "South African Rand", code: "ZAR", symbol: "R" },
  { name: "South Korean Won", code: "KRW", symbol: "₩" },
  { name: "Swedish Krona", code: "SEK", symbol: "kr" },
  { name: "Swiss Franc", code: "CHF", symbol: "CHF" },
  { name: "Taiwan Dollar", code: "TWD", symbol: "NT$" },
  { name: "Thai Baht", code: "THB", symbol: "฿" },
  { name: "Turkish Lira", code: "TRY", symbol: "₺" },
  { name: "Ukrainian Hryvnia", code: "UAH", symbol: "₴" },
  { name: "United Arab Emirates Dirham", code: "AED", symbol: "د.إ" },
  { name: "US Dollar", code: "USD", symbol: "$" },
  { name: "Vietnamese Dong", code: "VND", symbol: "₫" },
];
