export const CURRENCY_OPTIONS = [
  { label: "Australian Dollar (AUD) - $", value: "AUD" },
  { label: "Brazilian Real (BRL) - R$", value: "BRL" },
  { label: "British Pound (GBP) - £", value: "GBP" },
  { label: "Canadian Dollar (CAD) - CA$", value: "CAD" },
  { label: "Chinese Yuan (CNY) - ¥", value: "CNY" },
  { label: "Czech Koruna (CZK) - Kč", value: "CZK" },
  { label: "Danish Krone (DKK) - kr", value: "DKK" },
  { label: "Euro (EUR) - €", value: "EUR" },
  { label: "Hong Kong Dollar (HKD) - HK$", value: "HKD" },
  { label: "Hungarian Forint (HUF) - Ft", value: "HUF" },
  { label: "Indian Rupee (INR) - ₹", value: "INR" },
  { label: "Indonesian Rupiah (IDR) - Rp", value: "IDR" },
  { label: "Israeli New Shekel (ILS) - ₪", value: "ILS" },
  { label: "Japanese Yen (JPY) - ¥", value: "JPY" },
  { label: "Malaysian Ringgit (MYR) - RM", value: "MYR" },
  { label: "Mexican Peso (MXN) - MX$", value: "MXN" },
  { label: "New Zealand Dollar (NZD) - NZ$", value: "NZD" },
  { label: "Norwegian Krone (NOK) - kr", value: "NOK" },
  { label: "Philippine Peso (PHP) - ₱", value: "PHP" },
  { label: "Polish Złoty (PLN) - zł", value: "PLN" },
  { label: "Russian Ruble (RUB) - ₽", value: "RUB" },
  { label: "Saudi Riyal (SAR) - ﷼", value: "SAR" },
  { label: "Singapore Dollar (SGD) - S$", value: "SGD" },
  { label: "South African Rand (ZAR) - R", value: "ZAR" },
  { label: "South Korean Won (KRW) - ₩", value: "KRW" },
  { label: "Swedish Krona (SEK) - kr", value: "SEK" },
  { label: "Swiss Franc (CHF) - CHF", value: "CHF" },
  { label: "Taiwan Dollar (TWD) - NT$", value: "TWD" },
  { label: "Thai Baht (THB) - ฿", value: "THB" },
  { label: "Turkish Lira (TRY) - ₺", value: "TRY" },
  { label: "Ukrainian Hryvnia (UAH) - ₴", value: "UAH" },
  { label: "United Arab Emirates Dirham (AED) - د.إ", value: "AED" },
  { label: "US Dollar (USD) - $", value: "USD" },
  { label: "Vietnamese Dong (VND) - ₫", value: "VND" },
];

export type CurrencyOption = (typeof CURRENCY_OPTIONS)[number];
