import { Currency } from "../../types/TCreateTrip";

export const CURRENCY_OPTIONS: Currency[] = [
  { name: "Australian Dollar", code: "AUD", symbol: "$", decimalDigits: 2 },
  { name: "Brazilian Real", code: "BRL", symbol: "R$", decimalDigits: 2 },
  { name: "British Pound", code: "GBP", symbol: "£", decimalDigits: 2 },
  { name: "Canadian Dollar", code: "CAD", symbol: "CA$", decimalDigits: 2 },
  { name: "Chinese Yuan", code: "CNY", symbol: "¥", decimalDigits: 2 },
  { name: "Czech Koruna", code: "CZK", symbol: "Kč", decimalDigits: 2 },
  { name: "Danish Krone", code: "DKK", symbol: "kr", decimalDigits: 2 },
  { name: "Euro", code: "EUR", symbol: "€", decimalDigits: 2 },
  { name: "Hong Kong Dollar", code: "HKD", symbol: "HK$", decimalDigits: 2 },
  { name: "Hungarian Forint", code: "HUF", symbol: "Ft", decimalDigits: 0 },
  { name: "Indian Rupee", code: "INR", symbol: "₹", decimalDigits: 2 },
  { name: "Indonesian Rupiah", code: "IDR", symbol: "Rp", decimalDigits: 0 },
  { name: "Israeli New Shekel", code: "ILS", symbol: "₪", decimalDigits: 2 },
  { name: "Japanese Yen", code: "JPY", symbol: "¥", decimalDigits: 0 },
  { name: "Malaysian Ringgit", code: "MYR", symbol: "RM", decimalDigits: 2 },
  { name: "Mexican Peso", code: "MXN", symbol: "MX$", decimalDigits: 2 },
  { name: "New Zealand Dollar", code: "NZD", symbol: "NZ$", decimalDigits: 2 },
  { name: "Norwegian Krone", code: "NOK", symbol: "kr", decimalDigits: 2 },
  { name: "Philippine Peso", code: "PHP", symbol: "₱", decimalDigits: 2 },
  { name: "Polish Złoty", code: "PLN", symbol: "zł", decimalDigits: 2 },
  { name: "Russian Ruble", code: "RUB", symbol: "₽", decimalDigits: 2 },
  { name: "Saudi Riyal", code: "SAR", symbol: "﷼", decimalDigits: 2 },
  { name: "Singapore Dollar", code: "SGD", symbol: "S$", decimalDigits: 2 },
  { name: "South African Rand", code: "ZAR", symbol: "R", decimalDigits: 2 },
  { name: "South Korean Won", code: "KRW", symbol: "₩", decimalDigits: 0 },
  { name: "Swedish Krona", code: "SEK", symbol: "kr", decimalDigits: 2 },
  { name: "Swiss Franc", code: "CHF", symbol: "CHF", decimalDigits: 2 },
  { name: "Taiwan Dollar", code: "TWD", symbol: "NT$", decimalDigits: 0 },
  { name: "Thai Baht", code: "THB", symbol: "฿", decimalDigits: 2 },
  { name: "Turkish Lira", code: "TRY", symbol: "₺", decimalDigits: 2 },
  { name: "Ukrainian Hryvnia", code: "UAH", symbol: "₴", decimalDigits: 2 },
  {
    name: "United Arab Emirates Dirham",
    code: "AED",
    symbol: "د.إ",
    decimalDigits: 2,
  },
  { name: "US Dollar", code: "USD", symbol: "$", decimalDigits: 2 },
  { name: "Vietnamese Dong", code: "VND", symbol: "₫", decimalDigits: 0 },
];
